=== v1ncenz000/Verefoo/entities/version1/jsonSchemas/Host.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "active" : {
      "type" : "boolean"
    },
    "cores" : {
      "type" : "integer"
    },
    "cpu" : {
      "type" : "integer"
    },
    "diskStorage" : {
      "type" : "integer"
    },
    "fixedEndpoint" : {
      "type" : "string"
    },
    "maxVNF" : {
      "type" : "integer"
    },
    "memory" : {
      "type" : "integer"
    },
    "name" : {
      "type" : "string"
    },
    "nodeRef" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "node" : {
            "type" : "string"
          }
        },
        "additionalProperties" : false
      }
    },
    "supportedVNF" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "functionalType" : {
            "type" : "string",
            "enum" : [ "FIREWALL", "ENDHOST", "ENDPOINT", "ANTISPAM", "CACHE", "DPI", "DPI_S", "MAILCLIENT", "MAILSERVER", "NAT", "VPNACCESS", "VPNEXIT", "WEBCLIENT", "WEBSERVER", "FIELDMODIFIER", "FORWARDER", "LOADBALANCER", "STATEFUL_FIREWALL", "PRIORITY_FIREWALL", "WEB_APPLICATION_FIREWALL", "TRAFFIC_MONITOR" ]
          }
        },
        "additionalProperties" : false
      }
    },
    "type" : {
      "type" : "string",
      "enum" : [ "CLIENT", "SERVER", "MIDDLEBOX" ]
    }
  },
  "additionalProperties" : false
}

=== v1ncenz000/Verefoo/entities/version1/jsonExamples/Host.json
{
    "name": "singleHost",
    "type": "MIDDLEBOX",
    "cpu": 2,
    "cores": 8,
    "nodeRef": [
        {
            "node": "10.0.0.2"
        },
        {
            "node": "10.0.0.3"
        }
    ],
    "active": true,
    "memory": 1000,
    "diskStorage": 10000,
    "fixedEndpoint": "endpoint",
    "maxVNF": 2,
    "supportedVNF": [
        {
            "functionalType": "CACHE"
        },
        {
            "functionalType": "VPNEXIT"
        },
        {
            "functionalType": "VPNACCESS"
        },
        {
            "functionalType": "NAT"
        }
    ]
}
